self.trained_table = TableWidget()
self.trained_table.setBorderVisible(True)
self.trained_table.setBorderRadius(8)
self.trained_table.setAlternatingRowColors(True)
self.trained_table.setWordWrap(False)
self.trained_table.setColumnCount(4)
self.trained_table.setHorizontalHeaderLabels(["Character", "RVC", "Download", "Load"])
self.trained_table.horizontalHeader().setVisible(True)
self.trained_table.verticalHeader().setVisible(False)
self.trained_table.setColumnWidth(3, 500)
self.trained_table.setColumnWidth(2, 500)
self.trained_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
self.trained_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Fixed)
self.trained_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Fixed)
self.trained_table.horizontalHeader().setSectionResizeMode(3, QHeaderView.ResizeMode.Fixed)
self.trained_table.setSortingEnabled(True)
# self.trained_table.horizontalHeader().sectionClicked.connect(self.on_header_clicked)
self.trained_table.cellClicked.connect(parent.on_model_select)
self.trained_table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)

self.trained_table.setMinimumSize(800, 600)

self.untrained_table = TableWidget()
self.untrained_table.setColumnCount(3)
self.untrained_table.setBorderVisible(True)
self.untrained_table.setBorderRadius(8)
self.untrained_table.setHorizontalHeaderLabels(["Character", "RVC", "Load"])
self.untrained_table.horizontalHeader().setVisible(True)
self.untrained_table.setAlternatingRowColors(True)
self.untrained_table.setAlternatingRowColors(True)
self.untrained_table.verticalHeader().setVisible(False)
self.untrained_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeMode.Stretch)
self.untrained_table.horizontalHeader().setSectionResizeMode(1, QHeaderView.ResizeMode.Fixed)
self.untrained_table.horizontalHeader().setSectionResizeMode(2, QHeaderView.ResizeMode.Fixed)
self.untrained_table.setMinimumSize(800, 600)
# self.untrained_table.cellClicked.connect(parent.on_untrained_model_select)
self.untrained_table.setSortingEnabled(True)
self.untrained_table.setEditTriggers(QAbstractItemView.EditTrigger.NoEditTriggers)
self.filter_line_edit = SearchLineEdit()
self.filter_line_edit.setPlaceholderText("Filter...")
self.filter_line_edit.textChanged.connect(self.apply_filter)